name: CI Pipeline

on: 
  push:
    branches: 
      - main # Run the pipeline when code is pushed to main
  pull_request:
    branches:
      - main # Run the pipeline for pull requests to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use an Ubuntu environment for the pipeline

    steps:
      - name: Check out the code
        uses: actions/checkout@v2 # Checks out code so pipeline can access it

      - name: Install dependencies
        run: npm install # Install project dependencies
        working-directory: ./FrontEnd # Path to the package.json

      - name: 
        run: npm test # Run tests

