name: CI Pipeline

on: 
  push:
    branches: 
      - dev # Run the pipeline when code is pushed to dev
  pull_request:
    branches:
      - dev # Run the pipeline for pull requests to dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use an Ubuntu environment for the pipeline

    steps:
      - name: Check out the code
        uses: actions/checkout@v3 # Checks out code so pipeline can access it

      - name: Install dependencies
        run: npm install # Install project dependencies
        working-directory: ./FrontEnd # Path to package.json

      - name: 
        run: npm test # Run tests
        working-directory: ./FrontEnd # Path to package.json

