name: Signup and Login Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3 to avoid deprecation issues

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Update to v3 for compatibility with Node 16/20
        with:
          node-version: '16'  # Specify Node.js 16 to match the current version requirements

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
