# Generated by Django 5.1.1 on 2024-09-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
