# Generated by Django 5.1.1 on 2024-09-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegApi', '0003_instructor_last_login_instructor_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
