# Generated by Django 5.1.1 on 2024-09-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegApi', '0005_alter_instructor_instructor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.IntegerField(unique=True),
        ),
    ]
