# Generated by Django 5.1.1 on 2024-09-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegApi', '0006_alter_instructor_instructor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
