# Generated by Django 5.1.1 on 2024-10-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegApi', '0007_alter_instructor_instructor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('team_name', models.CharField(max_length=100)),
                ('selected_members', models.CharField(max_length=500)),
                ('selected_class', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
