# Generated by Django 5.1.1 on 2024-10-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegApi', '0008_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='team',
            name='password',
        ),
        migrations.AlterField(
            model_name='team',
            name='selected_class',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='selected_members',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=255),
        ),
    ]
